name: EaglerFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 3.3
description: Plugin for the Eagler Freedom server.
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
